@startuml

actor ユーザー

boundary ログイン画面
boundary ユーザー登録画面
control 必須チェックを実施
control 文字数チェックを実施
control パスワードと確認用パスワードが一致しているか確認する
control ユーザー名重複チェックを実施
control エラーを表示する
control 新規ユーザーを作成する
control 所持金情報を作成する
control 新規ユーザーを保存する
control 所持金情報を保存する
control エラーを表示する
control ユーザー登録画面を表示する
control ログイン画面を表示する
entity 登録済みユーザー一覧
entity 新規ユーザー
entity 所持金情報

'基本コース
ログイン画面 -down-> ユーザー登録画面を表示する: ログイン画面にあるユーザー登録画面へのリンクをクリック
ユーザー登録画面を表示する -right-> ユーザー登録画面
ユーザー登録画面 -right-> ユーザー
ユーザー -right-> 必須チェックを実施: ユーザー情報を入力して、登録ボタンをクリック
必須チェックを実施 -right-> 文字数チェックを実施
文字数チェックを実施 -right-> パスワードと確認用パスワードが一致しているか確認する
パスワードと確認用パスワードが一致しているか確認する -right-> ユーザー名重複チェックを実施
ユーザー名重複チェックを実施 -right-> 新規ユーザーを作成する
新規ユーザーを作成する -down-> 新規ユーザーを保存する
新規ユーザーを保存する -down-> 所持金情報を作成する
所持金情報を作成する -down-> 所持金情報を保存する
所持金情報を保存する -down-> ログイン画面を表示する
ログイン画面を表示する -down-> ログイン画面

ユーザー名重複チェックを実施 -up- 登録済みユーザー一覧
新規ユーザーを作成する -- 新規ユーザー
新規ユーザーを保存する -- 新規ユーザー
所持金情報を作成する -- 所持金情報
所持金情報を保存する -- 所持金情報

'代替コース
ユーザー -down-> ログイン画面を表示する: キャンセルボタンをクリックする
ログイン画面 -left-> ユーザー

必須チェックを実施  -up-> エラーを表示する : 必須チェックに引っかかった場合
文字数チェックを実施 -up-> エラーを表示する : 文字数チェックに引っかかった場合
パスワードと確認用パスワードが一致しているか確認する -up-> エラーを表示する : パスワードとパスワード(確認)\n同一チェックに引っかかった場合
ユーザー名重複チェックを実施 -up-> エラーを表示する : ユーザー名重複チェックに引っかかった場合
エラーを表示する --> ユーザー登録画面


@enduml