@startuml

class LoginController {
  login(String userName, String password)
}

class UserController {
  register(String userName, String password)
}

class LankingController {
  getLanking()
}

class LoginService {
  login(String userName, String password)
}

class UserService {
  register(String userName, String password)
}

class LankingService {
  getLanking()
}

class User(仮) {
  userId: String
  userName: String
  password: String
}

class Possession_money(仮) {
  userId: String
  money: BigDecimal
}

class UserBhv(仮) {
  insert(User user)
  selectEntity(CBCall<UserCB> cbLambda)
  outsideSql()
}

class Possession_moneyBhv(仮) {
  insert(Possession_money possession_money)
  update(Possession_money possession_money)
  selectEntity(CBCall<Possession_moneyCB> cbLambda)
}

class UserCB(仮) {

}

class Possession_moneyCB(仮) {

}

class UserSession {
  userId: String
}

class UserAccount {
  userId: String
  userName: String
  password: String
}

class Lanking {
  userInfoList: List<UserInfo>
}

class PossessionMoney {
  userId: String
  money: BigDecimal
}

class UserInfo {
  userId: String
  userName: String
  money: BigDecimal
}

Lanking o- UserInfo

@enduml